### ISSUE TITLE
Typo involving trailingZeroDisplay

### ISSUE THREAD

**Issue by sffc** [tc39/proposal-intl-numberformat-v3#48] opened 2021-07-01 18:11 UTC
Jeff Walden found a typo:

https://tc39.es/proposal-intl-numberformat-v3/out/numberformat/diff.html#sec-initializenumberformat step 24 should be "trailingZeroDisplay" (no initial cap)

**Comment by chicoxyzzy** [comment] 2021-07-02 07:34
Duplicate of https://github.com/tc39/proposal-intl-numberformat-v3/issues/42

**Closed** 2021-07-14 19:34 UTC
Labels: duplicate, editorial
